server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/open-cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      initial-size: 8
      max-active: 20
      min-idle: 8
      max-wait: 6000
      time-between-eviction-runs-millis: 300000
      min-evictable-idle-time-millis: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1

  redis:
    database: 0
    host: ${redis_host:localhost}
    password: ${redis_password:123456}
    port: ${redis_port:6379}
    timeout: 6000